name: diagnosa
description: Tugas Akhir Fajri Yuliana

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.2.0
  fluttertoast: ^2.2.3
  flutter_sweet_alert: ^0.1.0
  gradient_app_bar: ^0.0.1
  sqflite: ^1.1.0
  path_provider: ^0.4.1
  # simple_permissions: ^0.1.9
  permission_handler: '^1.0.1'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #  http_auth: ^0.2.1
  http: ^0.12.0
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/stetoskop.png
    - images/diagnosa.jpg
    - images/menu_diagnosa.png
    - images/menu_penyakit.png
    - images/p001.jpg
    - images/p002.jpg
    - images/p003.jpg
    - images/p004.jpg
    - images/p005.jpg
    - images/p006.jpg
    - images/p007.jpg
    - images/p008.jpg
    - images/p009.jpg
    - images/p010.jpg
    - images/p011.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat_regular.ttf
        - asset: fonts/montserrat_bold.ttf
          weight: 700
  #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages